# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

---
kind: pipeline
name: linux_aarch64_

platform:
  os: linux
  arch: arm64

steps:
- name: Install dependencies
  image: condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    DOCKER_IMAGE: condaforge/linux-anvil-aarch64
    #BINSTAR_TOKEN: $(BINSTAR_TOKEN)
    BINSTAR_TOKEN: ""
  commands:
    - pwd
    - ls -lah
    - export THISDIR="$( cd "$( dirname "$0" )" >/dev/null && pwd )"
    - export PROVIDER_DIR="$(basename $THISDIR)"
    - bash /home/conda/feedstock_root/"$PROVIDER_DIR"/build_steps.sh
    # TODO Test build artifacts
    - echo "Finished building"
