---
kind: pipeline
name: linux_aarch64_

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    DOCKER_IMAGE: condaforge/linux-anvil-aarch64
    #BINSTAR_TOKEN: ""
  commands:
    - . /opt/conda/bin/activate
    - export FEEDSTOCK_ROOT="$CI_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - ./.drone/build_steps.sh
    - echo "Done building"

