---
kind: pipeline
name: linux_aarch64_

platform:
  os: linux
  arch: arm64

steps:
- name: Install dependencies
  image: condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    DOCKER_IMAGE: condaforge/linux-anvil-aarch64
    #BINSTAR_TOKEN: $(BINSTAR_TOKEN)
    BINSTAR_TOKEN: ""
  commands:
    - ./.drone/build_and_install.sh
    - echo "Finished building"
