---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: linux_aarch64_
  image: condaforge/linux-anvil-aarch64
  commands:
    - yum install -y make git
    - curl -L -O https://github.com/Archiconda/build-tools/releases/download/0.2.0/Archiconda2-0.2.0-Linux-aarch64.sh
    - bash Archiconda2*.sh -b -p /root/archiconda2
    - export PATH="/root/archiconda2/bin:${PATH}"
    - source /root/archiconda2/bin/activate root
    - conda config --set add_pip_as_python_dependency false
    - conda install -c conda-forge conda-build --yes
    # - conda --version
    # - conda config --show
    # - conda list
    # Hardcode the config for testing for now
    - conda build -m ci_support/linux_.yaml .
    - export PACKAGE_NAME=`conda build -m ci_support/linux_.yaml . --output`
