# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

---
kind: pipeline
name: linux_aarch64_

platform:
  os: linux
  arch: arm64

steps:
- name: Install dependencies
  image: docker
  volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
  environment:
    CONFIG: linux_aarch64_
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    DOCKER_IMAGE: condaforge/linux-anvil-aarch64
    #BINSTAR_TOKEN: $(BINSTAR_TOKEN)
  commands:
    - ./.drone/run_docker_build.sh

