---
kind: pipeline
name: linux_aarch64_

platform:
  os: linux
  arch: arm64

build_commands: &build_commands
  - export FEEDSTOCK_ROOT="$CI_WORKSPACE"
  - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
  - export CI=drone
  - echo "Done building"

steps:
- name: Install and build
  image: condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    #BINSTAR_TOKEN: ""
  commands: *build_commands

