# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

---
# This pipeline is used to test various build configurations
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: Install dependencies test
  image: condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    DOCKER_IMAGE: condaforge/linux-anvil-aarch64
    BINSTAR_TOKEN: ""
  commands:
    - yum install -y make git
    - curl -L -O https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh
    - bash Archiconda3*.sh -b -p /root/archiconda3
    - export PATH="/root/archiconda3/bin:$PATH"
    #- . /root/archiconda3/bin/activate root
    - . /root/archiconda3/bin/activate
    #- conda config --set add_pip_as_python_dependency false
    #- conda install -c conda-forge conda-build --yes
    # Hardcode the config for testing
    #- conda build -m .ci_support/linux_aarch64_.yaml .
    #- export PACKAGE_NAME=`conda build -m ci_support/linux_.yaml . --output`
    #- ./.drone/build_and_install.sh
    - conda info
    - cat /root/.condarc
    - exit
    - conda install --yes --quiet conda-forge-ci-setup=2 conda-build -c conda-forge
    #- setup_conda_rc /drone/src /drone/src/recipe /drone/src/.ci_support/linux_aarch64_.yaml
    - run_conda_forge_build_setup
    - make_build_number /drone/src /drone/src/recipe /drone/src/.ci_support/linux_aarch64_.yaml
    - conda build /drone/src/recipe -m /drone/src/.ci_support/linux_aarch64_.yaml
    - echo "Finished building"

---
kind: pipeline
name: linux_aarch64_

platform:
  os: linux
  arch: arm64

steps:
- name: Install dependencies
  image: condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    DOCKER_IMAGE: condaforge/linux-anvil-aarch64
    #BINSTAR_TOKEN: $(BINSTAR_TOKEN)
    BINSTAR_TOKEN: ""
  commands:
    - ./.drone/build_and_install.sh
    - echo "Finished building"
