#!/usr/bin/env bash

# PLEASE NOTE: This script has been automatically generated by conda-smithy. Any changes here
# will be lost next time ``conda smithy rerender`` is run. If you would like to make permanent
# changes to this script, consider a proposal to conda-smithy so that other feedstocks can also
# benefit from the improvement.

set -xeuo pipefail

# Conda setup

# Source the base Conda environment
. /root/archiconda3/bin/activate || true
. /opt/conda/bin/activate || true

# Build

export PYTHONUNBUFFERED=1
FEEDSTOCK_ROOT="${CI_WORKSPACE}"
RECIPE_ROOT="${FEEDSTOCK_ROOT}/recipe"
CI_SUPPORT="${FEEDSTOCK_ROOT}/.ci_support"
CONFIG_FILE="${CI_SUPPORT}/${CONFIG}.yaml"
ARTIFACTS="${FEEDSTOCK_ROOT}/build_artifacts"

mkdir -p "${ARTIFACTS}"

#cat >~/.condarc <<CONDARC
#
#conda-build:
#  root-dir: ${ARTIFACTS}
#
#CONDARC

conda install --yes --quiet conda-forge-ci-setup=2 conda-build -c conda-forge

# set up the condarc
#setup_conda_rc "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"

# TODO Seems like the issue is here
# Script located here - https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/run_conda_forge_build_setup_linux

export CPU_COUNT=2
export PYTHONUNBUFFERED=1

conda config --set show_channel_urls true
conda config --set auto_update_conda false
conda config --set add_pip_as_python_dependency false

export "CONDA_BLD_PATH=/home/conda/feedstock_root/build_artifacts"

mkdir -p "${CONDA_PREFIX}/etc/conda/activate.d"
echo "export CONDA_BLD_PATH='${CONDA_BLD_PATH}'"         > "${CONDA_PREFIX}/etc/conda/activate.d/conda-forge-ci-setup-activate.sh"
echo "export CPU_COUNT='${CPU_COUNT}'"                  >> "${CONDA_PREFIX}/etc/conda/activate.d/conda-forge-ci-setup-activate.sh"
echo "export PYTHONUNBUFFERED='${PYTHONUNBUFFERED}'"    >> "${CONDA_PREFIX}/etc/conda/activate.d/conda-forge-ci-setup-activate.sh"

conda info
conda config --show-sources
conda list --show-channel-urls

# Commands above are taken from `run_conda_forge_build_setup`
#run_conda_forge_build_setup

# make the build number clobber
make_build_number "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"

conda build "${RECIPE_ROOT}" -m "${CONFIG_FILE}" \
    --clobber-file "${CI_SUPPORT}/clobber_${CONFIG}.yaml"

if [[ "${UPLOAD_PACKAGES}" != "False" ]]; then
    upload_package "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"
fi

touch "${ARTIFACTS}/conda-forge-build-done-${CONFIG}"
# verify that the end of the script was reached
#test -f "${ARTIFACTS}/conda-forge-build-done-${CONFIG}"
